export const ALERT_ACTIONS = {
  SET_ALERT: 'SET_ALERT',
  REMOVE_ALERT: 'REMOVE_ALERT'
};

export const PRODUCTS_RATINGS_ACTIONS = {
  GET_PRODUCTS: 'GET_PRODUCTS',
  GET_PRODUCT: 'GET_PRODUCT',
  CLEAR_PRODUCTS: 'CLEAR_PRODUCTS',
  SET_LOADING: 'SET_LOADING'
};