export const ALERT_ACTIONS = {
  SET_ALERT: 'SET_ALERT',
  REMOVE_ALERT: 'REMOVE_ALERT'
};

export const PRODUCTS_RATINGS_ACTIONS = {
  GET_PRODUCTS: 'GET_PRODUCTS',
  GET_PRODUCTS_FILTER: 'GET_PRODUCTS_FILTER',
  GET_PRODUCT: 'GET_PRODUCT',
  UPDATE_RATING_PRODUCT:'UPDATE_RATING_PRODUCT',
  DELETE_PRODUCT: 'DELETE_PRODUCT',
  GET_TOP_RATED_PRODUCT: 'GET_TOP_RATED_PRODUCT',
  CLEAR_PRODUCTS: 'CLEAR_PRODUCTS',
  SET_LOADING: 'SET_LOADING',
  STOP_LOADING:'STOP_LOADING'
};